name: "Check Build"
on:
  pull_request:
  push:
    branches:
      - master
      - develop
jobs:
  check:
    name: Flake Check (x86_64 only)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
    - uses: cachix/install-nix-action@v17
      with:
        name: nix-community
    - name: Retrieve /nix/store archive
      uses: actions/cache@v3
      id: cache-nix-store
      with:
        path: nix-store.dump
        key: nix-store-${{ hashFiles('flake.*') }}
        restore-keys: |
          nix-store-
    - name: Import /nix/store contents
      if: ${{ steps.cache-nix-store.outputs.cache-hit }}
      run: |
        if [[ -f nix-store.dump ]]; then
          nix-store --import < nix-store.dump || true
          rm nix-store.dump
        fi
    - run: |
        nix build .#checks.x86_64-linux.init-example-el
    - name: Export /nix/store contents
      if: ${{ !steps.cache-nix-store.outputs.cache-hit }}
      run: |
        nix-store --export $(nix-store -qR /nix/store/*-doom-emacs) > nix-store.dump
